language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: d6xLN9V5jMQUWQC0rbnhMt0FelvtLJbKZDmBK6wDRmT/mp4HNTAiNQ/v6qfmclpvBMA6hmx8Xl+vumLcMhFWxVyL1+ugOXL6pUA5OV9l+JPHy3r4yQTxl2opGkjRol7jtj9E/L9v4fuE6+de5wAVhpN51iFxZgxVfz+pN9SZ11g=
  app: bergems
  on:
    repo: benburwell/MCEMS-Site
